// <auto-generated />
namespace TestEntity3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class A002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A002));
        
        string IMigrationMetadata.Id
        {
            get { return "201410071613440_A002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
