// <auto-generated />
namespace AtlanticDX.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitMySQLTestA01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMySQLTestA01));
        
        string IMigrationMetadata.Id
        {
            get { return "201506070745270_InitMySQLTestA01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
