// <auto-generated />
namespace AtlanticDX.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InitDatabaseV23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDatabaseV23));
        
        string IMigrationMetadata.Id
        {
            get { return "201504110652082_InitDatabaseV23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
