// <auto-generated />
namespace AtlanticDX.ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InitDatabaseV20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDatabaseV20));
        
        string IMigrationMetadata.Id
        {
            get { return "201501310559404_InitDatabaseV20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
